{
 "title": "VK Streaming API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Max Value 5m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "message.count", "id": "1", "type": "max" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Counter of Posts",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "message.count", "id": "1", "type": "max" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "RAW data",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Posts Statistics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "message.count", "id": "1", "type": "avg" }
     ],
     "timeField": "date"
    },
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "message.count", "id": "1", "type": "avg" }
     ],
     "timeField": "date"
    }
   ]
  }
 ]
}