apiVersion: 1

datasources:
  - name: elasticsearch_docker
    type: elasticsearch
    access: proxy
    database: "data"
    url: http://docker_elasticsearch_1:9200
    jsonData:
      timeInterval: 60s
      timeField: "date"
      esVersion: 2
    isDefault: true
