# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./HW1
      run: if [ -e pom.xml ]; then mvn -B package --file pom.xml; fi
    
    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.9
        cache: pip
        architecture: x64
        cache-dependency-path: HW1/requirements.txt
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r HW1/requirements.txt
    
    - name: Generate data
      working-directory: ./HW1
      run: python generator.py -s 100K -real
    
    - name: Execute jar
      working-directory: ./HW1
      run: java -cp target/lab1-1.0-SNAPSHOT-jar-with-dependencies.jar com.yakovenko.lab1.MapReduceApp input output SECTORS TEMPERATURE --debug
      
    - name: Plot
      working-directory: ./HW1
      run: python plot.py -c
      
    - name: Update plot
      working-directory: ./HW1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output.png
        git commit -m "Update plot" output.png || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
