name: Spark App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./HW2
        run: mvn -B package --file pom.xml

      - name: Build the stack
        working-directory: ./HW2/docker
        run: docker-compose up -d --build

      - name: Show containers
        run: docker ps -a

      - name: Wait for containers
        run: sleep 10

      - name: Show containers
        run: docker ps -a

      - name: Test
        run: docker exec -t spark-hadoop /bin/bash -c "/root/start.sh com.yakovenko.lab2.SparkSQLApplication SparkSQLApplication lab2-1.0-SNAPSHOT-jar-with-dependencies.jar"

      - name: Debug test
        run: docker exec -t spark-hadoop /bin/bash -c "hdfs dfs -cat /user/root/inputs/part*"

      - name: Stop containers
        working-directory: ./HW2/docker
        if: always()
        run: docker-compose -f "docker-compose.yml" down
