name: Aggregation Service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build producer with Maven
        working-directory: ./HW3/producer
        run: mvn -B package --file pom.xml

      - name: Build consumer with Maven
        working-directory: ./HW3/consumer
        run: mvn -B package --file pom.xml

      - name: Build the stack
        working-directory: ./HW3/docker
        run: docker-compose up -d --build

      - name: Show containers
        run: docker ps -a

      - name: Wait for containers
        run: sleep 10

      - name: Check Elasticsearch
        run: curl -XGET "localhost:9200/"

      - name: Stop containers
        working-directory: ./HW3/docker
        if: always()
        run: docker-compose -f "docker-compose.yml" down
